README.md, css/news.css, news.html, news/javascrip.js, news/news.json
news update added. 
Add new news to news.json file in news folder to add to news data.
@vsvipul
=> News section update

contacts.html
The main changes made in this update are:
1. updated the litsoc contacts;
2. changed the tech society advisor
3. changes in the club coordis for nirmaan
4.removed repeated stac (bug)
=> updated the lit contacts

news/news.json
Corrected the news section for Crack The Code event. My name was wrongly mentioned as a participant whereas I was one of the 2 organizers and problem setters.
Edit: Squash and merge please.
=> Correct CrackTheCode news details.

senate.html
Adding the description for the seante and the UG Acad council.
=> added desc + names

hostel.html
=> added new hostel names

contacts.html, css/custom.css, cultural.html, hostel.html, literary.html, research.html, sports.html, technical.html
Now the pages look like this
@vsvipul check if it looks fine, I have checked and taken care for it to be working.
=> Added a link on every secy page to view their respective coordies

contacts.html
I have updated contacts.html.
In response to issue #27
Please check.
=> Updated contacts.html

senate.html
=> Created/Updated the table on Academic Secy Page

contacts.html
updated contact pages #32 @vsvipul @Signior-X
=> updated contacts

technical.html
Changed text to "society website" #35
=> changed text

contacts.html
updated research contacts #32 @vsvipul @Signior-X
=> research contacts updated

contacts.html
i have made the table to fit for mobile also. and also changed the UI of table. Fix #29 @vsvipul @Signior-X
=> contacts page are responsive now

research.html
=> fix issue 42

senate.html
Added the details of senate council members in the order specified
Fixes #49
=> Added necessary changes

contacts.html, contributors.html, cultural.html, hostel.html, index.html, literary.html, news.html, research.html, senate.html, sports.html, technical.html, wall_of_fame.html
Added the git repository link to the Links section in contributors page
=> Added 'want to contribute' link

technical.html
i want to make changes to line 109 of this file.
=> adding rel="noopener noreferrer"

contacts.html, contributors.html, cultural.html, hostel.html, index.html, literary.html, news.html, research.html, senate.html, sports.html, technical.html, wall_of_fame.html
- Changed the link reference position of new component to the `more` dropdown.
-  Closes #73
=> Moved news to more dropdown

.vscode/settings.json, contributors.html
=> Added an HTML target attribute to the contributors github link 

contributors.html, css/style.css
Added a new section which contains a anchor tag and a h2 element. The anchor tag links to the github repository. 
Fixes #54
=> Add WANT TO CONTRIBUTE with github repo link on contributors page

contacts.html
=> Move ACM-W to Research

senate.html
=> changed branch representative

contacts.html
=> fix https request

css/style.css, js/main.js, wall_of_fame.html
Screen shot of new looking of wall of fame are-
=> Add a new accordation part in wall of fame
